Create replace_all helper for sed (#8)

diff --git a/pulldozer b/pulldozer
--- a/pulldozer
+++ b/pulldozer
@@ -23,6 +23,61 @@ log_divider() {
   log_info "$(printf %70s '' | tr ' ' '=')"
 }
 
+# Helper for users who want something easier than sed
+replace_all() {
+  # Read and validate params
+  before="${1}"
+  shift
+  after="${1}"
+  shift
+  path_regex="${1}"
+  if [ -z "${after}" ]; then
+    die "Usage: replace_all 'search regex' 'replacement' 'file path regex' # last arg optional
+Example: replace_all 'colou?r' 'hue' 'README\.md'"
+  fi
+
+  # Check for GNU sed
+  if man sed | grep -qE '\bGNU\b'; then
+    gnu_sed_command='sed'
+  else
+    gnu_sed_command='gsed'
+    if ! command -v gsed > /dev/null; then
+      if command -v brew > /dev/null; then
+        log_info '`replace_all` requires gsed. Installing via Homebrew...'
+        if HOMEBREW_NO_ENV_HINTS=1 brew install gsed 2> /dev/null; then
+          log_info 'gsed installed successfully!'
+        else
+          die 'Failed to install gsed from Homebrew'
+        fi
+      fi
+      if ! command -v gsed > /dev/null; then
+        die 'Please try again after installing gsed (GNU sed).'
+      fi
+    fi
+  fi
+
+  # Determine char to use as sed delimiter
+  # TODO: Try using unprintable char(s) like \001 as delimiter?
+  delimiter=''
+  for delimiter_candidate in '/' ';' '@' '#' '_' ':' '%'; do
+    if ! printf %s "${before}${after}" | grep -qE "${delimiter_candidate}"; then
+      delimiter="${delimiter_candidate}"
+      break
+    fi
+  done
+  if [ -z "${delimiter}" ]; then
+    die 'replace_all params are too complex - no possible sed delimiter found'
+  fi
+
+  # Perform replacements
+  git grep -Il '' | grep -E "${path_regex:-.}" | while read -r path; do
+    # https://stackoverflow.com/a/1252191
+    "${gnu_sed_command}" -i -E \
+      ":a;N;\$!ba;s${delimiter}${before}${delimiter}${after}${delimiter}g" \
+      "${path}"
+  done
+}
+
 # Verify that cURL is installed
 if ! command -v curl > /dev/null; then
   die 'Please install cURL first.'
@@ -95,7 +150,9 @@ log_info 'Step 1/4: Refreshing local repo cache...'
 refresh_repo() {
   # Fetch latest repo commit if already cloned, otherwise shallow clone
   if [ -d .git ]; then
-    git fetch --depth 1 origin master 2> /dev/null
+    if ! git fetch --depth 1 origin master 2> /dev/null; then
+      die "Failed to fetch ${1}"
+    fi
     git reset --hard origin/master > /dev/null
     git clean -dfx > /dev/null
     git branch | grep -vE ' master$' \
