Print API response upon failure to create PR

diff --git a/pulldozer b/pulldozer
--- a/pulldozer
+++ b/pulldozer
@@ -285,7 +285,7 @@ create_pr() {
   # Push branch and open PR
   if ! git push --set-upstream origin "${branch_name}" > /dev/null 2>&1; then
     log_error "Failed to push to ${1}. Do you have write access?"
-    return
+    exit 1
   fi
   sleep 2
   api_response="$(
@@ -301,6 +301,11 @@ create_pr() {
       }
 EOF
   )"
+  if ! printf %s "${api_response}" | grep -q html_url; then
+    log_error "${api_response}"
+    log_error 'Created branch but failed to create PR! See error above.'
+    exit 1
+  fi
   log_info "Created $(printf %s "${api_response}" | grep -E '^  "html_url":' | cut -d'"' -f4)"
 }
 do_inside_each_repo create_pr
